'use strict';

/**
 * Phase 2 — hitlGateway.regression.test.js
 *
 * Mocked-dependency suite covering Phase 2 CR-02 + CR-03 on the BFF side:
 *   CR-02 — hitlGatewayMiddleware store key consistency. The previous code
 *           wrote under req.session.id and read under consentId; the function
 *           recordConsentDecision was called with 3 args but its signature
 *           takes 2 (the third was silently dropped).
 *   CR-03 — consentId is generated by crypto.randomUUID (128 bits of CSPRNG
 *           entropy) — not Math.random().toString(36).substr(2, 9).
 *
 * Test pattern follows CLAUDE.md "Test patterns: Regression vs. Integration":
 *   - configStore is mocked with TEST_CONFIG constants
 *   - session/auth middleware is shimmed
 *   - bankingAgentLangGraphService is mocked to inject requiresConsent flows
 *   - hitlGatewayMiddleware functions are NOT mocked — we exercise the real
 *     in-memory store to prove the keys align end-to-end.
 *
 * Note: bankingAgentRoutes mounts agentSessionMiddleware which calls
 * PingOne/oauthUserService. We mock the entire middleware module to bypass
 * the real session validation and inject req.session + req.agentContext
 * directly.
 */

const express = require('express');
const request = require('supertest');

jest.setTimeout(15000);

const TEST_CONFIG = {
  ff_hitl_enabled: 'true',
  confirm_threshold_usd: '500',
  mfa_threshold_usd: '500',
};

// ---------- mocks (must precede route require) ----------

jest.mock('../../services/configStore', () => ({
  getEffective: jest.fn((key) => TEST_CONFIG[key] || null),
  get: jest.fn((key) => TEST_CONFIG[key] || null),
  setRaw: jest.fn(),
}));

jest.mock('../../middleware/agentSessionMiddleware', () => ({
  agentSessionMiddleware: (req, res, next) => {
    req.session = req.session || {
      id: 'test-session-id',
      save: (cb) => cb && cb(),
    };
    req.agentContext = {
      userId: 'test-user-1',
      accessToken: 'fake-bearer-token',
      tokenEvents: [],
    };
    next();
  },
}));

jest.mock('../../services/bankingAgentLangGraphService', () => ({
  processAgentMessage: jest.fn(() =>
    Promise.resolve({
      requiresConsent: true,
      action: 'create_transfer',
      amount: 5000,
      details: { fromAccountId: 'acct-1', toAccountId: 'acct-2' },
      message: 'High-value transfer requires approval',
      tokenEvents: [],
    }),
  ),
}));

jest.mock('../../services/appEventService', () => ({
  logEvent: jest.fn(() => Promise.resolve()),
}));

jest.mock('../../services/tokenChainService', () => ({
  trackTokenEvent: jest.fn(() => Promise.resolve()),
}));

// hitlGatewayMiddleware is REAL — that is the module under test.
// Reset its global state between tests so prior consents don't bleed.

/**
 * Build the test app with a fixed session ID so POST /consent can pass the
 * CR-01 session-ownership check. Every request from the same app shares the
 * same session ID, mirroring a real browser session.
 */
function buildApp({ sessionId = 'test-session-fixed' } = {}) {
  jest.resetModules();
  // re-apply mocks (jest preserves the factories across resetModules,
  // but we have to clear the global pendingConsents map ourselves).
  global.pendingConsents = {};

  const app = express();
  app.use(express.json());

  // Inject a session shim before the agent router so req.session.id is set.
  app.use((req, res, next) => {
    req.session = {
      id: sessionId,
      save: (cb) => cb && cb(),
    };
    next();
  });

  const router = require('../../routes/bankingAgentRoutes');
  app.use('/api/banking-agent', router);
  return app;
}

// ---------- tests ----------

describe('hitlGateway regression — CR-02 store key alignment + CR-03 secure consentId', () => {
  beforeEach(() => {
    global.pendingConsents = {};
    jest.clearAllMocks();
  });

  test('POST /message returns 428 with a consentId stored under consentId (not sessionId)', async () => {
    const app = buildApp();

    const res = await request(app)
      .post('/api/banking-agent/message')
      .send({ message: 'transfer $5000 to checking' });

    expect(res.status).toBe(428);
    expect(res.body.requiresConsent).toBe(true);
    expect(typeof res.body.consentId).toBe('string');
    expect(res.body.consentId.length).toBeGreaterThan(0);

    // CR-02: the in-memory store must be keyed by the returned consentId,
    // not by the session id. If the old (broken) code is restored, this
    // assertion fails because the entry lives under req.session.id.
    expect(global.pendingConsents[res.body.consentId]).toBeDefined();
    expect(global.pendingConsents[res.body.consentId].action).toBe('create_transfer');
  });

  test('generated consentId is a 36-char hex UUID (CR-03 — 128 bits of entropy)', async () => {
    const app = buildApp();

    const res = await request(app)
      .post('/api/banking-agent/message')
      .send({ message: 'transfer $5000' });

    expect(res.status).toBe(428);
    // crypto.randomUUID produces standard RFC 4122 v4 format:
    // xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx (36 chars including 4 hyphens)
    expect(res.body.consentId).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    );
    expect(res.body.consentId.length).toBe(36);
  });

  test('POST /consent with approved=true persists decision="approve" under consentId', async () => {
    const app = buildApp();

    const init = await request(app)
      .post('/api/banking-agent/message')
      .send({ message: 'transfer $5000' });
    const consentId = init.body.consentId;

    const resp = await request(app)
      .post('/api/banking-agent/consent')
      .send({ consentId, approved: true });

    expect(resp.status).toBe(200);
    expect(resp.body.recorded).toBe(true);
    expect(resp.body.approved).toBe(true);

    // CR-02: the decision is recorded under the consentId AND the value
    // is the string 'approve' (not the consentId itself, as the old code
    // accidentally did by swapping arg positions).
    expect(global.pendingConsents[consentId].decision).toBe('approve');
  });

  test('POST /consent with approved=false persists decision="reject" under consentId', async () => {
    const app = buildApp();

    const init = await request(app)
      .post('/api/banking-agent/message')
      .send({ message: 'transfer $5000' });
    const consentId = init.body.consentId;

    const resp = await request(app)
      .post('/api/banking-agent/consent')
      .send({ consentId, approved: false });

    expect(resp.status).toBe(200);
    expect(resp.body.recorded).toBe(true);
    expect(resp.body.approved).toBe(false);
    expect(global.pendingConsents[consentId].decision).toBe('reject');
  });

  test('POST /consent with non-UUID consentId returns 400 (validation rejects before lookup)', async () => {
    // CR-01 fix: the route now validates consentId format (UUID v4) before
    // touching the store, so a malformed key gets 400 — not 500 from a throw.
    // This also blocks prototype-pollution keys like __proto__ or constructor.
    const app = buildApp();

    const resp = await request(app)
      .post('/api/banking-agent/consent')
      .send({ consentId: 'not-a-real-id-deadbeef', approved: true });

    expect(resp.status).toBe(400);
    expect(resp.body.error).toMatch(/consentId/i);
  });

  test('POST /consent with valid UUID but unknown consentId returns 404', async () => {
    // A well-formed UUID that simply does not exist in the store must return
    // 404, not 500. No phantom "approved" record.
    const app = buildApp();

    const fakeId = '00000000-0000-4000-8000-000000000001';
    const resp = await request(app)
      .post('/api/banking-agent/consent')
      .send({ consentId: fakeId, approved: true });

    expect(resp.status).toBe(404);
    expect(resp.body.error).toMatch(/not found/i);
  });

  test('POST /consent with missing consentId returns 400', async () => {
    const app = buildApp();

    const resp = await request(app)
      .post('/api/banking-agent/consent')
      .send({ approved: true });

    expect(resp.status).toBe(400);
    expect(resp.body.error).toMatch(/consentId/);
  });

  test('two consents in the same session get distinct unguessable IDs', async () => {
    const app = buildApp();

    const a = await request(app)
      .post('/api/banking-agent/message')
      .send({ message: 'transfer $5000' });
    const b = await request(app)
      .post('/api/banking-agent/message')
      .send({ message: 'transfer $6000' });

    expect(a.body.consentId).toBeTruthy();
    expect(b.body.consentId).toBeTruthy();
    expect(a.body.consentId).not.toBe(b.body.consentId);

    // Both must be present in the store under their own keys — confirms
    // session-id keying is gone.
    expect(global.pendingConsents[a.body.consentId]).toBeDefined();
    expect(global.pendingConsents[b.body.consentId]).toBeDefined();
  });
});
