'use strict';
/**
 * GET /api/admin/mcp-gateway/config
 *
 * Returns mock gateway status, current configuration summary, and a generated
 * PingGateway mcp.json route file for real-PingGateway deployments.
 *
 * No authentication required on GET — gateway status is visible to the admin
 * config page which handles auth at the route level in server.js.
 */
const express = require('express');
const http = require('http');
const configStore = require('../services/configStore');
const router = express.Router();

// ---------------------------------------------------------------------------
// Health probe to the mock gateway
// ---------------------------------------------------------------------------
function probeGatewayHealth(gatewayUrl) {
    return new Promise((resolve) => {
        const url = new URL(gatewayUrl.replace(/\/$/, '') + '/health');
        const opts = { hostname: url.hostname, port: parseInt(url.port || '3005', 10), path: url.pathname, method: 'GET', timeout: 3000 };
        const req = http.request(opts, (res) => {
            let data = '';
            res.on('data', (chunk) => { data += chunk; });
            res.on('end', () => {
                try { resolve({ running: res.statusCode === 200, response: JSON.parse(data) }); }
                catch { resolve({ running: res.statusCode === 200, response: null }); }
            });
        });
        req.on('error', () => resolve({ running: false, response: null }));
        req.on('timeout', () => { req.destroy(); resolve({ running: false, response: null }); });
        req.end();
    });
}

// ---------------------------------------------------------------------------
// Generate a PingGateway-compatible mcp.json route configuration
// ---------------------------------------------------------------------------
function buildPingGatewayMcpJson(cfg) {
    const gatewayUri   = cfg.gatewayResourceUri || 'https://mcp-gw.example.com';
    const upstreamUrl  = cfg.upstreamMcpUrl     || 'http://localhost:8080';
    const authServer   = cfg.authServerUrl       || 'https://auth.pingone.com/{envId}/as';
    const paEndpoint   = cfg.pingAuthorizeEndpoint || '';
    const paWorkerId   = cfg.pingAuthorizeWorkerId  || '';

    return {
        _comment: 'PingGateway MCP route configuration — generated by BX Finance Gateway Config UI',
        _docs: 'https://docs.pingidentity.com/pinggateway/latest/mcp-integration',
        routes: [
            {
                name: 'mcp-banking-route',
                condition: '${find(request.uri.path, \'/mcp\')}',
                heap: [
                    {
                        name: 'McpAuditFilter',
                        type: 'McpAuditFilter',
                        config: { enabled: true }
                    },
                    {
                        name: 'McpProtectionFilter',
                        type: 'McpProtectionFilter',
                        config: {
                            resourceUri: gatewayUri,
                            authorizationServer: authServer,
                            requiredScopes: ['banking:read', 'banking:write'],
                        }
                    },
                    {
                        name: 'McpValidationFilter',
                        type: 'McpValidationFilter',
                        config: {
                            acceptedOrigins: ['https://your-app.example.com'],
                            requireJsonRpc: true,
                            requireAcceptHeader: true,
                        }
                    },
                    ...(paEndpoint ? [{
                        name: 'PingAuthorizeFilter',
                        type: 'PingAuthorizeFilter',
                        config: {
                            endpoint: paEndpoint,
                            workerId: paWorkerId,
                        }
                    }] : []),
                    {
                        name: 'ReverseProxyHandler',
                        type: 'ReverseProxyHandler',
                        config: {
                            handler: { type: 'ClientHandler' },
                        }
                    },
                ],
                handler: 'ReverseProxyHandler',
                filters: [
                    'McpAuditFilter',
                    'McpProtectionFilter',
                    'McpValidationFilter',
                    ...(paEndpoint ? ['PingAuthorizeFilter'] : []),
                ],
                baseURI: upstreamUrl,
            }
        ]
    };
}

// ---------------------------------------------------------------------------
// GET /api/admin/mcp-gateway/config
// ---------------------------------------------------------------------------
router.get('/config', async (req, res) => {
    const gatewayUrl = process.env.MCP_GATEWAY_HTTP_URL || 'http://localhost:3005';
    const gatewayEnabled = !!process.env.MCP_GATEWAY_HTTP_URL;
    const devBypass = process.env.MCP_GW_DEV_BYPASS === 'true';

    const { running, response: healthResponse } = await probeGatewayHealth(gatewayUrl);

    const pingone_resource_mcp_gateway_uri = configStore.getEffective('pingone_resource_mcp_gateway_uri') || '';

    const cfg = {
        gatewayResourceUri:    process.env.MCP_GW_RESOURCE_URI     || pingone_resource_mcp_gateway_uri,
        upstreamMcpUrl:        process.env.MCP_OLB_WS_URL           || configStore.getEffective('mcp_server_url') || 'ws://localhost:8080',
        authServerUrl:         (() => {
            const envId = configStore.getEffective('pingone_environment_id') || '{envId}';
            const region = configStore.getEffective('pingone_region') || 'com';
            return `https://auth.pingone.${region}/${envId}/as`;
        })(),
        pingAuthorizeEndpoint: process.env.PINGAUTHORIZE_ENDPOINT || '',
        pingAuthorizeWorkerId: process.env.PINGAUTHORIZE_WORKER_ID || '',
    };

    res.json({
        mock: {
            enabled: gatewayEnabled,
            running,
            devBypass,
            url: gatewayUrl,
            health: healthResponse,
        },
        config: cfg,
        envVars: {
            required: {
                MCP_GW_RESOURCE_URI:    process.env.MCP_GW_RESOURCE_URI    ? '••••' : 'NOT SET',
                MCP_GW_CLIENT_ID:       process.env.MCP_GW_CLIENT_ID       ? '••••' : 'NOT SET',
                MCP_GW_CLIENT_SECRET:   process.env.MCP_GW_CLIENT_SECRET   ? '••••' : 'NOT SET',
                PINGONE_TOKEN_ENDPOINT: process.env.PINGONE_TOKEN_ENDPOINT  ? '••••' : 'NOT SET',
                MCP_OLB_RESOURCE_URI:   process.env.MCP_OLB_RESOURCE_URI   ? '••••' : 'NOT SET',
                MCP_INVEST_RESOURCE_URI:process.env.MCP_INVEST_RESOURCE_URI ? '••••' : 'NOT SET',
            },
            optional: {
                MCP_GATEWAY_HTTP_URL:    process.env.MCP_GATEWAY_HTTP_URL   || '(not set — gateway routing disabled)',
                MCP_GW_DEV_BYPASS:       process.env.MCP_GW_DEV_BYPASS      || 'false',
                PINGAUTHORIZE_ENDPOINT:  process.env.PINGAUTHORIZE_ENDPOINT  || '(not set — permit-all)',
                PINGAUTHORIZE_WORKER_ID: process.env.PINGAUTHORIZE_WORKER_ID || '(not set)',
            },
        },
        pingGatewayJson: buildPingGatewayMcpJson(cfg),
    });
});

module.exports = router;
